server {
    listen 8080;
    index index.html index.php;
    server_name .localhost;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access`.log;
    root /var/www/html/public;
    # client_max_body_size 100m;

    location /storage/ {
        # Usando root, o Nginx vai procurar em: /var/www/ + /storage/ + arquivo.jpg
         
        alias /var/www/html/storage/;


        # IMPORTANTE: Remova o try_files que aponta para o index.html
        # Se não achar a imagem, deve dar 404 e PARAR ali.
        try_files $uri =404;

        access_log off;
        log_not_found off;
        expires max;

        # Adicione headers de CORS para o Angular não bloquear a imagem
        add_header Access-Control-Allow-Origin *;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app-php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

    }
    client_max_body_size 15M;
    server_tokens off;

     # Hide PHP headers
    fastcgi_hide_header X-Powered-By;
    fastcgi_hide_header X-CF-Powered-By;
    fastcgi_hide_header X-Runtime;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
