services:
  app-php:
    build: .      
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    networks:
      - app_network
  web-nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ../site.conf:/etc/nginx/conf.d/site.conf
      - ../:/var/www/html
    restart: always
    depends_on:
      - app-php
    networks:
      - app_network
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleet_control      
      MYSQL_PASSWORD: william
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: william
    volumes:
      - ../database/mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge

