name: Deploy Backend

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/fleet_control/fleet_control-back-end
            git pull origin master
            docker exec fleet_control-back-end composer install --no-dev --optimize-autoloader
            docker exec fleet_control-back-end php artisan migrate --force
            docker exec fleet_control-back-end php artisan config:cache
            docker exec fleet_control-back-end php artisan route:cache
